language: python

# recommended by travis support:
sudo: required

python:
  - "2.6" # sublime text 2 compilation
  - "3.3" # sublime text 3 complication

# install dependencies:
install:
  - pip install flake8

# Run tests:
script:
  - flake8 .

# disable all email build notifications:
notifications:
  email: false
